server:
  port : 8082
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: saa
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    repositories:
      bootstrap-mode: default
      database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console1